common:
  mode: "dev"  # dev || pro
  listen_port: 9000
  db_uri: "postgres://postgres:admin1234@localhost:5432/peonbot"
  redis_uri: "redis://localhost:6379/0"
  allow_viabots:
    - "mmbq_bot"

tgbot:
  update_mode: "poll" # poll || webhook
  auto_set_webhook: false
  bot_token: ""
  hook_url: ""

ignore_word:
  - "台"
